/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea1progra;


import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

import java.util.ArrayList;

/**
 *
 * @author Jonatan
 */
public class FrameDoctor extends javax.swing.JFrame {
    
    ArrayList<Integer> listaCodigosDoctor = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameDoctor.class.getName());

    /**
     * Creates new form GrameDoctor
     */
    public FrameDoctor() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombreDoctor = new javax.swing.JTextField();
        txtTelefonoDoctor = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        botonCapturar = new javax.swing.JButton();
        labelCodigo = new javax.swing.JLabel();
        labelNombreDoctor = new javax.swing.JLabel();
        labelTelefonoDoctor = new javax.swing.JLabel();
        labelEspecialidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Doctor");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono Doctor");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Especialidad");

        txtCodigo.setBackground(new java.awt.Color(0, 255, 255));
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        txtNombreDoctor.setBackground(new java.awt.Color(0, 255, 255));
        txtNombreDoctor.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreDoctorKeyPressed(evt);
            }
        });

        txtTelefonoDoctor.setBackground(new java.awt.Color(0, 255, 255));
        txtTelefonoDoctor.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefonoDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoDoctorKeyPressed(evt);
            }
        });

        txtEspecialidad.setBackground(new java.awt.Color(0, 255, 255));
        txtEspecialidad.setForeground(new java.awt.Color(255, 255, 255));
        txtEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEspecialidadKeyPressed(evt);
            }
        });

        botonCapturar.setBackground(new java.awt.Color(0, 255, 255));
        botonCapturar.setForeground(new java.awt.Color(255, 255, 255));
        botonCapturar.setText("Capturar Datos");
        botonCapturar.addActionListener(this::botonCapturarActionPerformed);
        botonCapturar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonCapturarKeyPressed(evt);
            }
        });

        labelCodigo.setForeground(new java.awt.Color(255, 255, 255));

        labelNombreDoctor.setForeground(new java.awt.Color(255, 255, 255));

        labelTelefonoDoctor.setForeground(new java.awt.Color(255, 255, 255));

        labelEspecialidad.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCapturar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(73, 73, 73)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(txtNombreDoctor)
                                .addComponent(txtTelefonoDoctor)
                                .addComponent(txtEspecialidad)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelTelefonoDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(188, 188, 188)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelNombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefonoDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonCapturar)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTelefonoDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCapturarActionPerformed
        // TODO add your handling code here:
        botonCapturar();
    }//GEN-LAST:event_botonCapturarActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        txtNombreDoctor.requestFocus(); 
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtNombreDoctorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDoctorKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        txtTelefonoDoctor.requestFocus(); 
        }
    }//GEN-LAST:event_txtNombreDoctorKeyPressed

    private void txtTelefonoDoctorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoDoctorKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        txtEspecialidad.requestFocus(); 
        }
    }//GEN-LAST:event_txtTelefonoDoctorKeyPressed

    private void txtEspecialidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspecialidadKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        botonCapturar.requestFocus(); 
        }
    }//GEN-LAST:event_txtEspecialidadKeyPressed

    private void botonCapturarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonCapturarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         botonCapturar();
         }
    }//GEN-LAST:event_botonCapturarKeyPressed
public void botonCapturar(){
            // TODO add your handling code here:
    Integer codigo;
    String nombreDoctor;
    String telefonoDoctor;
    String especialidad;
    codigo=Integer.parseInt(txtCodigo.getText());
    

    if(listaCodigosDoctor.contains(codigo)){
    JOptionPane.showMessageDialog(null, "El código ya existe");
    limpiar();
    txtCodigo.requestFocus();
    return;
}

    nombreDoctor=txtNombreDoctor.getText();
    telefonoDoctor=txtTelefonoDoctor.getText();
    especialidad=txtEspecialidad.getText();
    //++++++++++++++++++SE instancia la calse++++++++++++++
    
    Doctor doctor=new Doctor();
    //       Enviando Valores a la clase+++++++++++++++++++
    doctor.codigo=codigo;
    doctor.nombreDoctor=nombreDoctor;
    doctor.telefonoDoctor=telefonoDoctor;
    doctor.especialidad=especialidad;
    
    
    //+++++++++++++Impresion de resultados+++++++++++++++++
    
    labelCodigo.setText(doctor.codigo+"");
    labelNombreDoctor.setText(doctor.nombreDoctor);
    labelTelefonoDoctor.setText(doctor.telefonoDoctor);
    labelEspecialidad.setText(doctor.especialidad);
    limpiar();
    listaCodigosDoctor.add(codigo);
    JOptionPane.showMessageDialog(null, "Registro Ingresado");
    String texto = "DOCTOR\n" +
               "Codigo: " + codigo + "\n" +
               "Nombre: " + nombreDoctor + "\n" +
               "Telefono: " + telefonoDoctor + "\n" +
               "Especialidad: " + especialidad;

ArchivoTexto.guardarTexto(codigo + "," + nombreDoctor + "," + telefonoDoctor + "," + especialidad, "doctores.csv");
}
    public void limpiar(){
    txtCodigo.setText("");
    txtNombreDoctor.setText("");
    txtTelefonoDoctor.setText("");
    txtEspecialidad.setText("");
    txtCodigo.requestFocus();  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameDoctor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCapturar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelEspecialidad;
    private javax.swing.JLabel labelNombreDoctor;
    private javax.swing.JLabel labelTelefonoDoctor;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtNombreDoctor;
    private javax.swing.JTextField txtTelefonoDoctor;
    // End of variables declaration//GEN-END:variables
}
